[package]
name = "heretek"
version = "0.9.0"
edition = "2024"
description = "GDB TUI Dashboard for the understanding of vast knowledge"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wcampbell0x2a/heretek"
categories = ["development-tools"]
keywords = ["gdb", "tui", "debugging", "embedded", "gdbserver"]
exclude = ["book/", "images/", ".github/"]

[dependencies]
ansi-to-tui = "8.0.1"
anyhow = "1.0.104"
chrono = "0.4.45"
clap = { version = "4.6.6", features = ["derive"] }
clap-cargo = "0.18.0"
deku = { version = "0.20.3", default-features = false, features = ["alloc", "std"] }
env_logger = "0.11.11"
evalexpr = "13.1.0"
hex = "0.4.3"
log = "0.4.33"
nix = { version = "0.31", features = ["term"] }
once_cell = "1.21.4"
ratatui = "0.30.2"
regex = "1.13.1"
tui-input = "0.15.3"
arborium = { version = "2.18.1", features = ["lang-c", "lang-cpp", "lang-rust"] }

[dev-dependencies]
insta = "1.48.0"
test-assets-ureq = "0.6.2"
libc = "0.2.189"
rstest = "0.26"

[profile.release]
strip = true

# Release(dist) binaries are setup for maximum runtime speed, at the cost of CI time
[profile.dist]
inherits = "release"
codegen-units = 1
lto = true
strip = true
