Output images/readme.gif
Set Theme ayu
Set Padding 2
Set FontSize 12
Set Width 1000
Set Height 1000

Type "./target/release/heretek"
Enter
Sleep 2s

Type "i"
Type "file test-assets/test_render_app/a.out"
Enter
Sleep 2s

Type "break main"
Enter
Sleep 2s

Type "run"
Enter
Sleep 5s

Type "si"
Enter
Sleep 5s
Type "si"
Enter
Sleep 5s
Type "si"
Enter
Sleep 5s

Escape
Tab
Sleep 5s
Tab
Sleep 5s
Tab
Sleep 5s
Tab
Sleep 5s
Tab
Sleep 5s

